### ISSUE TITLE
ground truth rotation

### ISSUE THREAD

**Issue by kimkj38** [82magnolia/piccolo#5]
Thanks for your great work first.
I have a question about the gt rotation in data_utils.py

I don't understand why the red box parts are needed.
could you explain about this?

![image](https://user-images.githubusercontent.com/76815825/232781375-24a08532-ee65-4e88-9199-f16ab0629aa6.png)

**Comment by 82magnolia** [comment]
Hi, sorry for the late reply. The conversion is made so that the rotation matrix is in accordance with the coordinate frame assumed by PICCOLO. Specifically, the rotation matrix ensures that `make_pano` or `cloud2idx` functions in `utils.py` to function properly (it is just a way to align the coordinate frame from the original dataset's point cloud to that of PICCOLO).
